import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "AlgoAnimate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} min-h-screen flex flex-col`}>
          {/* Header */}
          <Header />

          {/* Main content */}
          <main className="flex-1">{children}</main>

          {/* Footer */}
          <footer className="bg-gray-50 py-7 mt-auto">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p>Visualize . Understand . Code better</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
