import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "AlgoAnimate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`$inter.className `}>
          <Header />

          <main className="min-h-screen">{children}</main>

          {/* footer */}
          <footer className="bg-gray-50 py-15">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p> Visualize . Understand . Code better </p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
